# Практическая работа №1: Исследование алгоритмов формирования аддитивных цепочек
Выполнил студент гр. 0304 Люлин Денис Викторович, вариант 38

## Цель работы
Формирование представления о аддитивных цепочках, выработать умение
составлять и применять алгоритмы для нахождения минимальных
аддитивных цепочек для заданного числа, привить навык использования
систем компьютерной математики для реализации алгоритмов.
## Основные теоретические положения
Аддитивной цепочкой для $ n \in \mathbb{N} $ называется последовательность натуральных чисел
$$ 1 = a_0, a_1, ..., a_r = n, $$
где каждый элемент последователньости равен сумме каких-то двух предыдущих:
$$ a_i = a_j + a_k, \quad k \le j \le i, \quad i = 1, 2, ..., r $$

$l(n) = r$ - наименьшая длина аддитивной цепочки для $ n \in \mathbb{N} $.

Для метода множителей: $ \quad l(mn) \le l(m) + l(n)$

Для бинарного метода: $l(n) = \lambda(n) + \nu(n) - 1, \quad$ где $\lambda (n) = \lfloor lb(n) \rfloor, \nu(n)$ - вес Хэмминга числа $n$ (количество единиц в двоичной записи).

Для m-арного метода: $ \quad l(n) \le m - 2 + (k + 1)t, \quad$ где $m = 2^k, n = \sum_{j = 0}^t d_j m^{t-j} $

Для SX-метода: $\quad l(n) \le \lambda (n) + \nu (n) - 1$


Пара $ (j, k), 0 \le k \le j < i $ называется **шагом** $i$.Если существует более одной пары $(j, k)$, полагаем $j$ наибольшим.

### Виды шагов:
* удвоение: $ j = k = i - 1 $
* звёздный шаг: $ j = i - 1 $ (линейный шаг)
* малый шаг: $ \lambda (a_i) = \lambda (a_i - 1) $

### Свойства видов шагов:
* шаг 1 - всегда удвоение
* удвоение - звёздный шаг, но никогда не малый
* если $i$-ый шаг не малый, то $(i+1)$-ый шаг либо малый, либо звёздный, либо оба
* за удвоением всегда следует звёздный шаг
* если $(i+1)$-ый шаг не звёздный и не малый, то $i$-ый шаг должен быть малым

### Теорема:

Если аддитивная цепочка содержит $d$ и $f = r - d$ неудвоений, то $n \le 2^{d-1} F_{f+3}$, где $F_j$ - число Фиббоначи

### Следствие:

Если аддитивная цепочка содержит $f$ удвоений и $S$ малых шагов, то

${S \le f \le} {S \over {1 - lb(\varphi)}}$, где $\varphi = {{\sqrt{5} + 1} \over 2} $ - золотое сечение

### Алгоритм Брауэра:

Для $n \in \mathbb{N}$ при заданном $k \in \mathbb{N}$ можно построить цепочку Брауэра с помощью рекуррентной формулы:

$$ B_k (n) =
\begin{cases}
1, 2, 3, ..., 2^k - 1, \quad n < 2^k \\
B_k (q), 2q, 4q, ..., 2^k q, n, \quad n \ge 2^k
\end{cases} \\
q = \lfloor {n \over 2^k} \rfloor
$$

Длина цепочки
$$l_B (n) = j(k + 1) + 2^k - 2,$$
при условии, что $jk \le \lambda (n) \le (j+1)k$

Длина будет минимальной для больших $n$, если положить $k = \lambda \lambda (n) - 2 \lambda \lambda \lambda (n)$

**Ход алгоритма:**

* Задаётся некий параметр $k$ для $n$.
Вычисляются вспомогательные числа:
$$
d = 2^k, \hspace{0.2cm} q_1 = [ {n \over d} ], \hspace{0.2cm} r_1 = n \hspace{0.2cm} mod \hspace{0.2cm} d => n = q_1 d + r_1 \quad (0 \le r_1 < d) \\
q_2 = [ {q_1 \over d} ], \hspace{0.2cm} r_2 = q_1 \hspace{0.2cm} mod \hspace{0.2cm} d => q_1 = q_2 d + r_2 \quad (0 \le r_2 < d)
$$
* Данная процедура продолжается, пока не появится $q_s < d.$ Следовательно, $q_{s-1} = q_s d + r_s$
* Таким образом, n имеет вид
$$ n = 2^k q_1 + r_1 = 2^k (2^k q_2 + r_2) + r_1 = ...\\
... = 2^k (2^k (... (2^k q_s + r_s ) ... ) + r_2 ) + r_1 . $$

$$B_n (n): 1, 2, 3, ..., 2^k - 1, \\
2q_s, 4q_s, 8q_s, ..., 2^k q_s, 2^k q_s + r_s, \\
2q_{s-1}, 4q_{s-1}, 8q_{s-1}, ..., 2^k q_{s-1}, 2^k q_{s-1} + r_{s-1}, \\
..., \\
..., 2^k q_1, 2^k q_1 + r_1 = n.$$

### Алгоритм Яо:

* Обладает такой же вычислительной мощностью, что и алгоритм Брауэра
* Выбирается $k \ge 2$, $n$ раскладывается в $2^k$-ой системе счисления:
$$ n = \sum_{i = 0}^j a_i 2^{ik} , a_j \ne 0 $$
* Введём функцию d:
$$ d(z) = \sum_{i: a_i = z} 2^{ik} $$

**Ход алгоритма:**

* Базовая последовательность: $1, 2, 4, ..., 2^{\lambda(n)}$
* Вычисление значений $d(z)$ для всех $z \in \{ 1, 2, ..., 2^k - 1\}, \quad d(z) \ne 0$
* Вычисление $zd(z)$ для всех $z$
* n раскладывается в виде
$$ n = \sum_{z = 1}^{2^k - 1} zd(z) $$

## Постановка задачи
Реализовать точные и приближённые алгоритмы нахождения минимальных
аддитивных цепочек с использованием системы компьютерной математики
SageMath, провести анализ алгоритмов. Полученные результаты
содержательно проинтерпретировать.
## Порядок выполнения работы
1. Вручную (т.е. не реализовывая алгоритм на Sage) построить последовательность
вычислений бинарным методом и методом множителей
для $x^n$ для 2-3 значений $n$ (значение $n > 30$ выбираются
студентом самостоятельно). Сравнить количество операций для
каждого метода, сделать выводы.
2. Реализовать алгоритм Брауэра (для нечётных вариантов) и алгоритм
Яо (для чётных вариантов) для вычисления приближённых
аддитивных цепочек для различных чисел при варьировании
параметра $k$, сопоставить длины полученных аддитивных цепочек
с минимальной аддитивной цепочкой для заданного числа. Сделать
выводы.
3. Реализовать алгоритм дробления вектора индексов для нахождения
минимальной звёздной цепочки для заданного числа. Протестировать
алгоритм минимум для 5 значений $n > 1000$. Указать,
сколько времени потребовалось на поиск цепочки и какая цепочка
получилась. Сравнить с предыдущими методами, сделать выводы.
4. Проверить гипотезу Шольца–Брауэра для всех натуральных
$1 \le n \le 12$ на алгоритме дробления вектора индексов. Результаты
оформить в виде таблицы. Сделать выводы.
5. Найти или предложить собственные модификации алгоритмов и
привести описание модификаций. Реализовать модифицированные
алгоритмы и сравнить их мощность.

## Выполнение работы.
1. Построим последовательность вычислений бинарным методом для $x^n$ для $n = 48, 63$.
**Бинарный метод**

$n = 48$:

| step | N  | Y    | Z    |
|------|----|------|------|
| 0    | 48 | 1    | x    |
| 1    | 24 | 1    | x^2  |
| 2    | 12 | 1    | x^4  |
| 3    | 6  | 1    | x^8  |
| 4    | 3  | 1    | x^16 |
| 5    | 1  | x^16 | x^32 |
| 6    | 0  | x^48 | x^32 |

Метод занял 6 операций.

$n = 63$:

| step | N  | Y    | Z    |
|------|----|------|------|
| 0    | 63 | 1    | x    |
| 1    | 31 | x    | x^2  |
| 2    | 15 | x^3  | x^4  |
| 3    | 7  | x^7  | x^8  |
| 4    | 3  | x^15 | x^16 |
| 5    | 1  | x^31 | x^32 |
| 6    | 0  | x^63 | x^32 |

Метод занял 10 операций (во время шагов 2-5 происходило по 2 операции умножения).

**Метод множителей**

$n = 48$:

$$48 = pq = 2 \cdot 24$$
$$y = x^2$$
$$y = (y^8)^3 = (((y^2)^2)^2)^3 = (((y^2)^2)^2)^2 \cdot ((y^2)^2)^2$$

Метод занял 6 операций.

$n = 63$:

$$63 = pq = 3 \cdot 21$$
$$y = x^3$$
$$y = (y^3)^7 = (y^3)^6 \cdot y^3 = ((y^3)^2)^3 \cdot y^3$$

Метод занял 8 операций.

Для числа $n = 48$ бинарный метод и метод множителей завершились за 6 операций. Для числа $n = 63$ бинарный метод занял 10 операций, а метод множителей - 8 операций.

Бинарный метод работает хуже для чисел, в двоичной записи которых много единиц, так как количество операций зависит от веса Хэмминга числа $n$: $l(n) = \lambda(n) + \nu(n) - 1$. Метод множителей работает быстрее, потому что не привязан к системе счисления, а ищет первый простой множитель. Количество операций метода множителей не превосходит суммы количества операций этого метода для каждого множителя. Поэтому этот метод эффективнее для чисел, близких к $2^k-1$.

2. Реализуем алгоритм Яо для вычисления приближённых аддитивных цепочек.

In [11]:
import time
from math import log, ceil

# разложение числа n в 2^k-чной с.с.
def factor_2k(n, k):
    digits = []
    div = 1 << k
    while n > 0:
        digits.append(n % div)
        n //= div
    return digits

# функция возвращает d(z)
# добавляет элементы в цепочку chain
def yao_d(z, k, digits, chain):
    d = 0
    for i in range(len(digits)):
        if digits[i] == z:
            s = 1 << (i*k)
            if d != 0:
                chain.append(d+s)
            d += s
    return d

# функция возвращает z*d(z) и добавляет значения в цепочку
# вычисление по бинарному алгоритму
def yao_zdz(z, dz, chain):
    y, old_dz = 0, dz
    while z != 0:
        if dz not in chain:
            chain.append(dz)
        if z % 2 != 0:
            if y != 0:
                chain.append(y+dz)
            y += dz
        dz *= 2
        z //= 2
    return y

# алгоритм Яо
def yao_chain(n, k):
    digits = factor_2k(n, k)
    # базовая посл-ть от 2^0 до 2^jk, j - max индекс цифры в 2^k-чной с.с.
    chain = Sequence(1<<i for i in range((len(digits)-1)*k+1))
    # вычисление d(z) для всех (кроме 0) цифр числа n в 2^k-чной с.с.
    dz = {z:yao_d(z, k, digits, chain) for z in set(filter(lambda x: x != 0, digits))}
    # вычисление z*d(z)
    zdz = Sequence(yao_zdz(i, dz[i], chain) for i in dz)
    # сумма всех z*d(z) с добавлением в цепочку
    n = zdz[0]
    for i in range(1, len(zdz)):
        n += zdz[i]
        chain.append(n)
    return chain




# тестирование
test_set = [1033, 2000, 1040, 4096, 1100]
for val in test_set:
    print("TESTING YAO'S ALGORITHM ON VALUE ", val)
    for k in range(3, 7):
        begin = time.time()
        chain = yao_chain(val, k)
        end = time.time()
        print("k = ", k, "\t CHAIN: ", *chain)
        print("l(n) = ", len(chain)-1, "\t Time elapsed = ",
              round(end-begin, 5), " sec\tMinimal length = ", ceil(log(val, 2)))
    print("\n")

TESTING YAO'S ALGORITHM ON VALUE  1033
k =  3 	 CHAIN:  1 2 4 8 16 32 64 128 256 512 9 1024 1033
l(n) =  12 	 Time elapsed =  0.0461  sec	Minimal length =  11
k =  4 	 CHAIN:  1 2 4 8 16 32 64 128 256 9 512 1024 1033
l(n) =  12 	 Time elapsed =  0.00015  sec	Minimal length =  11
k =  5 	 CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 9 1033
l(n) =  12 	 Time elapsed =  0.00023  sec	Minimal length =  11
k =  6 	 CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 9 1033
l(n) =  12 	 Time elapsed =  0.00027  sec	Minimal length =  11


TESTING YAO'S ALGORITHM ON VALUE  2000
k =  3 	 CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 1536 192 448 1552 2000
l(n) =  15 	 Time elapsed =  0.00024  sec	Minimal length =  11
k =  4 	 CHAIN:  1 2 4 8 16 32 64 128 256 80 208 512 768 1024 1792 2000
l(n) =  15 	 Time elapsed =  0.00018  sec	Minimal length =  11
k =  5 	 CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 192 448 960 1040 2000
l(n) =  15 	 Time elapsed =  0.00019  sec	Minimal length =  11
k =  6 	 CHAIN:  1 2 4 8 16 3

Работа алгоритма Яо была протестирована для чисел, больших 1000, при разных значениях параметра $k$. Алгоритм занял порядка $10^{-4}$ секунды при каждом запуске. При этом при разных $k$ длина цепочки была одинаковой. Также время работы для разных $k$ было примерно одинаковым.

Длина цепочки превышала минимальную оценку в среднем на 1-2 элемента. За минимальную оценку было взято значение $\lceil log_{2}n \rceil$, полученное с помощью бинарного метода. Больше всего от минимальной оценки отличалась длина аддитивной цепочки для числа 2000 (длина цепочки - 15, оценка - 11).

3. Реализуем алгоритм дробления вектора индексов для нахождения минимальной звёздной цепочки для заданного числа.

In [10]:
import time
from math import log, ceil, floor
# получение следующего вектора индексов
# или части [r_start; r_end] (для перебора половины вектора)
# возвращает True, если вектор получен;
#            False, если был передан вектор из единиц
def next_vector(vec, start, end):
    i = end
    # найти самую старшую позицию с r_i > 1 и уменьшить r_i на 1
    while vec[i] == 1 and i >= start:
        i -= 1
    if i < start:
        return False
    vec[i] -= 1
    # выставить все следующие индексы в max
    for j in range(i+1, end+1):
        vec[j] = j+1
    return True

# вычислить аддитивную цепочку по вектору индексов
def get_chain(vec):
    chain = [1]
    for i in vec:
        chain.append(chain[-1] + chain[i-1])
    return chain

# алгоритм дробления вектора индексов
def index_vector_chain(n):
    if n < 3:
        return list(range(1, n+1))
    for m in range(ceil(log(n, 2)), floor(log(n, 2))+bin(n).count('1')):
        vec = list(range(1, m+1))
        q = m//2
        vec[q-1] += 1 # увеличить на 1, чтобы в цикле получить нужное значение
        while next_vector(vec, 0, q-1):
            a = get_chain(vec)
            if a[m] == n:
                return a
            elif n >= a[q] + m - q and n <= a[q] * 2**(m-q):
                while next_vector(vec, q, len(vec)-1):
                    a = get_chain(vec)
                    if a[m] == n:
                        return a
                # снова выставить правую часть в максимум и перебирать левую половину
                for i in range(q, len(vec)):
                    vec[i] = i+1




# тестирование
test_set = [1033, 2000, 1040, 4096, 1100]
for val in test_set:
    print("TESTING INDEX VECTOR ALGORITHM ON VALUE ", val)
    begin = time.time()
    chain = index_vector_chain(val)
    end = time.time()
    print("CHAIN: ", *chain)
    print("l(n) = ", len(chain)-1, "\t Time elapsed = ",
              round(end-begin, 5), " sec\tMinimal length = ", ceil(log(val, 2)))
    print("\n")

TESTING INDEX VECTOR ALGORITHM ON VALUE  1033
CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 1032 1033
l(n) =  12 	 Time elapsed =  81.39031  sec	Minimal length =  11


TESTING INDEX VECTOR ALGORITHM ON VALUE  2000
CHAIN:  1 2 4 8 16 32 64 128 256 384 400 800 1600 2000
l(n) =  13 	 Time elapsed =  364.29522  sec	Minimal length =  11


TESTING INDEX VECTOR ALGORITHM ON VALUE  1040
CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 1040
l(n) =  11 	 Time elapsed =  0.00014  sec	Minimal length =  11


TESTING INDEX VECTOR ALGORITHM ON VALUE  4096
CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 2048 4096
l(n) =  12 	 Time elapsed =  4e-05  sec	Minimal length =  12


TESTING INDEX VECTOR ALGORITHM ON VALUE  1100
CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 1088 1096 1100
l(n) =  13 	 Time elapsed =  2656.14354  sec	Minimal length =  11




Алгоритм был протестирован для тех же чисел, что и алгоритм Яо. Длины полученных звёздных цепочек получились такими же, как для алгоритма Яо, для всех чисел, кроме 2000. Для него длина цепочки равна 13, тогда как в алгоритме Яо - 15. Однако алгоритм дробления вектора индексов работает намного дольше алгортма Яо: от нескольких минут до десятков минут (кроме чисел $1040 = 2^{10}+2^{4}$ и $4096=2^{12}$, для которых перебор оканчивается сразу). Такое долгое время работы объясняется тем, что в алгоритме происходит перебор различных векторов индексов, отчего алгоритм имеет факториальную сложность: $O(\sum (m-1)!)$. Перебор гарантирует, что будет найдена аддитивная цепочка минимальной длины.

4. Проверим гипотезу Шольца-Брауэра для чисел $1 \leq n \leq 12$ с помощью алгоритма дробления вектора индексов.

Гипотеза Шольца-Брауэра представляется следующим неравенством:

$$l(2^n-1) \leq l(n)+n-1.$$

Она была доказана только для звёздных цепочек.

Код для проверки:

In [9]:
for i in range (1, 13):
    # вычислить цепочку алгоритмом дробления вектора индексов
    chain_2n = index_vector_chain(2**i-1)
    chain_n = index_vector_chain(i)
    print("n =", i, end='')
    if len(chain_2n)-1 <= len(chain_n)+i-2:
        print("\tTRUE\t", len(chain_2n)-1, '<=', len(chain_n)+i-2)
    else:
        print("\tFALSE")
        print(chain_n)
        break


n = 1	TRUE	 0 <= 0
n = 2	TRUE	 2 <= 2
n = 3	TRUE	 4 <= 4
n = 4	TRUE	 5 <= 5
n = 5	TRUE	 7 <= 7
n = 6	TRUE	 8 <= 8
n = 7	TRUE	 10 <= 10
n = 8	TRUE	 10 <= 10
n = 9	TRUE	 12 <= 12
n = 10	TRUE	 13 <= 13
n = 11	TRUE	 15 <= 15
n = 12	TRUE	 15 <= 15


Оформив результат в виде таблицы, получим:


| N  | Верно |Неравенство|
|----|-------|-----------|
|  1 | Да    |    0 <= 0 |
|  2 | Да    |    2 <= 2 |
|  3 | Да    |    4 <= 4 |
|  4 | Да    |    5 <= 5 |
|  5 | Да    |    7 <= 7 |
|  6 | Да    |    8 <= 8 |
|  7 | Да    |  10 <= 10 |
|  8 | Да    |  10 <= 10 |
|  9 | Да    |  12 <= 12 |
| 10 | Да    |  13 <= 13 |
| 11 | Да    |  15 <= 15 |
| 12 | Да    |  15 <= 15 |

Таким образом, гипотеза Шольца-Брауэра была проверена для всех чисел $1 \leq n \leq 12.$ Неравенство оказалось верно во всех случаях.

## Вывод

В данной работе были исследованы алгоритмы построения минимальных аддитивных цепочек для различных чисел.

Были реализованы алгоритмы Яо и дробления вектора инедексов. На приведённых входных алгоритм Яо давал неоптимальный результат, в отличие от алгоритма дробления вектора индексов. Однако алгоритм Яо работает на несколько порядков быстрее. С помощью алгоритма дробления вектора индексов была проверена гипотеза Шольца-Брауэра для чисел $1 \leq n \leq 12.$.