# Практическая работа №1: Исследование алгоритмов формирования аддитивных цепочек

Выполнил студент гр. 0304 Алексеев Роман, вариант 26.

## Цель работы

Формирование представления о аддитивных цепочках, выработать умение составлять и применять алгоритмы для нахождения минимальных аддитивных цепочек для заданного числа, привить навык использования систем компьютерной математики для реализации алгоритмов.

## Основные теоретические положения

Под аддитивной цепочкой понимается последовательность чисел, где каждый элемент равен сумме двух любых предыдущих элементов 
$$ 1 = a_0, a_1, ..., a_r = n $$ 
где $n \in ℕ$.

$l(n) = r$ - наименьшая длина аддитивной цепочки для $n \in ℕ$.

Для метода множителей: $ l(mn) \le l(m) + l(n) $

Для m-арного метода: $ l(n) \le m - 2 + (k + 1)t $, $ (m = 2^k, n = \sum_{j = 0}^t d_j m^{t-j}) $

Для SX-метода: $ l(n) \le \lambda (n) + \nu (n) - 1 $

### Свойства аддитивных цепочек

* Все аддитивные цепочки возрастающие:
$ 1 = a_0 < a_1 < ... < a_r = n $
* Если два числа одинаковы, то одно из них может быть опущено
* Пара $ (j, k) $, $ 0 \le k \le j \le i $ называется шагом $i$
* Если существует более чем одна пара $ (j, k) $, полагаем, что $ j $ - наибольший

### Виды шагов

* Удовоение: $ j = k = i -1 $
* Звёздный (линейный): $ j = i - 1 $
* Малый: $ \lambda (a_i) = \lambda (a_i-1) $

### Свойства шагов

* Шаг 1 всегда удвоение
* Удвоение - звёздный шаг, но никогда не малый
* За удвоением всегда следует звёздный шаг
* Если $ i $-ый шаг не малый, то $(i + 1)$-й шаг либо малый, либо звёздный, либо и тот, и другой
* Если $(i + 1)$-й шаг ни звёздный, ни малый, то $ i $-ый шаг должен быть малым

### Теорема

Если аддитивная цепочка включает $d$ удвоений и $f = r - d$ неудвоений, то $$n \le 2^{d-1}F_{f+3}$$ где $F_i$ - число Фибоначи

### Следствие

Если аддитивная цепочка включает $f$ неудвоений и $s$ малых шагов, то $$s \le f \le {S \over {1 - lb(\varphi)}}$$ где $ \varphi = {\sqrt{5} + 1 \over 2} $ - золотое сечение

### Приближенные алгоритмы нахождения аддитивных цепочек

### Алгоритм Брауэра

Для $n \in ℕ$ при заданном $k \in ℕ$ можно построить цепочку Брауэра с помощью рекуррентной формулы:

$$ B_k (n) =
\begin{cases}
1, 2, 3, ..., 2^k - 1, \quad n < 2^k \\
B_k (q), 2q, 4q, ..., 2^k q, n, \quad n \ge 2^k
\end{cases} \\
q = \lfloor {n \over 2^k} \rfloor
$$

Данная цепочка будет иметь длину $$ l_{B}(n) = j(k + 1) + 2^k - 2 $$ при условии, что $ jk \le  \lambda (n) \le (j + 1)k $

Длина будет минимальной для больших $n$, если $ k = \lambda (\lambda (n)) - 2 \lambda (\lambda (\lambda (n))) $

**Ход алгоритма:**

* Задаётся некий параметр $k$ для $n$.
Вычисляются вспомогательные числа:
$$
d = 2^k, \hspace{0.2cm} q_1 = [ {n \over d} ], \hspace{0.2cm} r_1 = n \hspace{0.2cm} mod \hspace{0.2cm} d => n = q_1 d + r_1 \quad (0 \le r_1 < d) \\
q_2 = [ {q_1 \over d} ], \hspace{0.2cm} r_2 = q_1 \hspace{0.2cm} mod \hspace{0.2cm} d => q_1 = q_2 d + r_2 \quad (0 \le r_2 < d)
$$
* Данная процедура продолжается, пока не появится $q_s < d.$ Следовательно, $q_{s-1} = q_s d + r_s$
* Таким образом, n имеет вид
$$ n = 2^k q_1 + r_1 = 2^k (2^k q_2 + r_2) + r_1 = ...\\
... = 2^k (2^k (... (2^k q_s + r_s ) ... ) + r_2 ) + r_1 . $$

$$B_n (n): 1, 2, 3, ..., 2^k - 1, \\
2q_s, 4q_s, 8q_s, ..., 2^k q_s, 2^k q_s + r_s, \\
2q_{s-1}, 4q_{s-1}, 8q_{s-1}, ..., 2^k q_{s-1}, 2^k q_{s-1} + r_{s-1}, \\
..., \\
..., 2^k q_1, 2^k q_1 + r_1 = n.$$

### Алгоритм Яо:

* Обладает такой же вычислительной мощностью, что и алгоритм Брауэра
* Выбирается $k \ge 2$, $n$ раскладывается в $2^k$-ой системе счисления:
$$ n = \sum_{i = 0}^j a_i 2^{ik} , a_j \ne 0 $$
* Введём функцию d:
$$ d(z) = \sum_{i: a_i = z} 2^{ik} $$

**Ход алгоритма:**

* Базовая последовательность: $1, 2, 4, ..., 2^{\lambda(n)}$
* Вычисление значений $d(z)$ для всех $z \in \{ 1, 2, ..., 2^k - 1\}, \quad d(z) \ne 0$
* Вычисление $zd(z)$ для всех $z$
* n раскладывается в виде
$$ n = \sum_{z = 1}^{2^k - 1} zd(z) $$

## Постановка задачи

Реализовать точные и приближённые алгоритмы нахождения минимальных аддитивных цепочек с использованием системы компьютерной математики SageMath, провести анализ алгоритмов. Полученные результаты содержательно проинтерпретировать

## Выполнение работы
Можно сделать текст курсивом с помощью *звёздочек* или _нижнего подчёркивания_. А можно сделать текст полужирным с помощью **двойных звёздочек** или __двойного нижнего подчёркивания__. _**Даже можно скомбинировать!**_ 

Для монотонного шрифта используется `символ машинного апострофа` (который находится на клавише Ё).

Jupyter Notebook поддерживает формулы $ \LaTeX $. Попробуем посчитать в SageMath следующий предел:
\\[
  \lim\limits_{x \to 0}\frac{\sin x}x
\\]

1. Вручную (т.е. не реализовывая алгоритм на Sage) построить последовательность вычислений бинарным методом и методом множителей для $𝑥^𝑛$ для 2-3 значений 𝑛 (значение 𝑛 > 30 выбираются студентом самостоятельно). Сравнить количество операций для каждого метода, сделать выводы.

**n = 42:**<br>

`Бинарный метод:`<br>

$ n = 42_{10} = 101010_{2} = 2^{3}*5 + 2^{2}*0 + 2^{1}*1 + 2^{0}*0 $

$ d_0 = 5, \space d_1 = 0, \space d_2 = 1, \space d_3 = 0 $

$ x, \space x^5, \space x^{10}, \space x^{20}, \space x^{21}, \space x^{42} $

Метод занял 6 операций

`Метод множителей`:<br>

$ n = 42, \space p = 2, \space q = 21 $

$ x, \space x^2 => y = x^2 $

$ y, \space y^2, \space y^3, \space y^6, \space y^7, \space y^{21} $

$ y^{21} = (x^2)^{21} = x^{42} $

Метод занял 6 операций

**n = 63:**<br>

`Бинарный метод:`<br>

$ n = 63_{10} = 111111_2 = 2^5 * 1 + 2^4 * 1 + 2^3 * 1 + 2^2 * 1 + 2^1 * 1 + 2^0 * 1 $

$ d_0 = 1, \space d_1 = 1, \space d_2 = 1, \space d_3 = 1, \space d_4 = 1, \space d_5 = 1 $

$ x, \space x^2, \space x^3, \space x^6, \space x^7, \space x^{14}, \space x^{15}, \space x^{30}, \space x^{31}, \space x^{62}, \space x^{63} $

Метод занял 11 операций 

`Метод множителей`:<br>

$ n = 63, \space p = 3, \space q = 21 $

$ x, \space x^2, \space x^3 => y = x^3 $

$ y, \space  y^2, \space  y^3, \space  y^6, \space  y^7, \space  y^{21} $

$ y^{21} = (x^3)^{21} = x^{63} $

Метод занял 9 операций


**Сравнение результатов**

Для $ n = 42 $ и бинарный метод, и метод множителей заняли 6 операций, для $ n = 63 $ бинарный метод занял 11 операций, а метод множителей - 9 операций.
Бинарный метод работает медленей метода множителей для чисел, в двоичной записи которых преобладают единицы.




2.  Реализовать алгоритм Брауэра (для нечётных вариантов) и алгоритм Яо (для чётных вариантов) для вычисления приближённых аддитивных цепочек для различных чисел при варьировании 1 параметра 𝑘, сопоставить длины полученных аддитивных цепочек с минимальной аддитивной цепочкой для заданного числа. Сделать выводы.

**Алгоритм Яо**

In [1]:
from math import log
import time

# Разложение числа n в 2^k-ой системе счисления
def change_numeral_system(number, k):
    new_number = []
    base = 2**k
    while number > 0:
        new_number.append(number % base)
        number = number // base    
    return new_number

# Вычисление значений ф-и d(z)
def dz_function(z, number, k, chain):
    dz = 0
    for i in range(len(number)):
        if number[i] == z:
            s = 1 << (i * k)
            if dz != 0:
                chain.append(dz + s)
            dz += s
    return dz
    
# Вычисление zd(z)
def zdz_function(z, dz, chain):
    y, old_dz = 0, dz
    while z != 0:
        if dz not in chain:
            chain.append(dz)
        if z % 2 != 0:
            if y != 0:
                chain.append(y+dz)
            y += dz
        dz *= 2
        z //= 2
    return y    

# Алгоритм Яо
def algYao(digit, k):
    chain = []
    number = change_numeral_system(digit, k)
    # Базовая последовательность
    base_chain = [2**i for i in range(floor(log(digit, 2)) + 1)]
    chain += base_chain
    # d(z)
    dz = {z: dz_function(z, number, k, chain) for z in set(filter(lambda x: x != 0, number))}
    # z*d(z)
    zdz = [zdz_function(z, dz[z], chain) for z in dz]
    n = zdz[0]
    for i in zdz[1:]:
        n += i
        chain.append(n)
    return chain
    

numbers = [1127, 1689, 1993, 2101, 4137]
for n in numbers:
    print('n =', n)
    print('Длина минимальной аддитивной цепочки:', ceil(log(n, 2)))
    for k in range(2, 8):
        time_start = time.perf_counter()
        print('k =', k)
        chain = algYao(n, k)
        print('Длинна аддитивной цепочки:', len(chain)-1)
        print('Аддитивная цепочка:', *chain, sep=' ')
        print('Time: {0:.5f} с\n'.format(time.perf_counter() - time_start))
        print()
    print('\n')

n = 1127
Длина минимальной аддитивной цепочки: 11
k = 2
Длинна аддитивной цепочки: 15
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 68 1092 3 1124 1127
Time: 0.00043 с


k = 3
Длинна аддитивной цепочки: 15
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 3 7 1088 1120 1127
Time: 0.00021 с


k = 4
Длинна аддитивной цепочки: 15
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 96 3 7 1120 1127
Time: 0.00018 с


k = 5
Длинна аддитивной цепочки: 15
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 96 3 7 1120 1127
Time: 0.00017 с


k = 6
Длинна аддитивной цепочки: 15
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 1088 3 7 39 1127
Time: 0.00021 с


k = 7
Длинна аддитивной цепочки: 15
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 3 7 39 103 1127
Time: 0.00018 с




n = 1689
Длина минимальной аддитивной цепочки: 11
k = 2
Длинна аддитивной цепочки: 16
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 17 1041 68 324 648 1689
Time: 0.00022 с


k = 3
Длинна

Алгоритм Яо был запущен для чисел 1127, 1689, 1993, 3071, 4137 в системах счисления с основаниями от 2 до 7 включительно. Разница между длинами аддитивных цепочек при разных k не превышает 1-2, при этом ни в одном случае не удалось получить аддитивную цепочку минимальной длины. Минимальная длина расчитывался по формуле $ lb(n) $, где n - исходное число.

3. Реализовать алгоритм дробления вектора индексов для нахождения минимальной звёздной цепочки для заданного числа. Протестировать алгоритм минимум для 5 значений 𝑛 > 1000. Указать, сколько времени потребовалось на поиск цепочки и какая цепочка получилась. Сравнить с предыдущими методами, сделать выводы.

**Алгоритм дроблени вектора индексов**

In [2]:
from math import log
import time

def next_ind_vec(part):
    for i in range(len(part) - 1, 0, -1):
        if part[i] > 1:
            part[i] -= 1
            for j in range(i + 1, len(part)):
                part[j] = j + 1
            return part
    return []

def search_chain(ind_vec):
    chain = [1]
    for i in ind_vec:
        chain.append(chain[-1] + chain[i-1])
    return chain

def splitt_vector_index(n):
    if n < 3:
        return [a for a in range(1, n+1)]
    for m in range(ceil(log(n, 2)), floor(log(n, 2)) + bin(n).count("1")):
        q = m // 2
        fix_part = [a for a in range(1, q+1)]
        var_part = [a for a in range(q+1, m+1)]
        while len(fix_part):   
            chain = search_chain(fix_part + var_part)
            a_min = chain[q] + m - q
            a_max = chain[q]*2**(m-q)
            if a_min <= n <= a_max:
                while len(var_part):      
                    chain = search_chain(fix_part + var_part)
                    if chain[-1] == n:
                        return search_chain(fix_part + var_part)
                    var_part = next_ind_vec(var_part)
            fix_part = next_ind_vec(fix_part)
            var_part = [i for i in range(q+1, m+1)]

numbers = [1127, 1689, 1993, 2101, 4137]
for n in numbers:
    time_start = time.perf_counter()
    print('n =', n)
    print('Длина минимальной аддитивной цепочки:', ceil(log(n, 2)))
    chain = splitt_vector_index(n)
    print('Длинна аддитивной цепочки:', len(chain)-1)
    print('Аддитивная цепочка:', *chain, sep=' ')
    print('Time: {0:.5f} с\n'.format(time.perf_counter() - time_start))

n = 1127
Длина минимальной аддитивной цепочки: 11
Длинна аддитивной цепочки: 13
Аддитивная цепочка: 1 2 4 6 7 14 28 56 112 224 448 896 1120 1127
Time: 43.60010 с

n = 1689
Длина минимальной аддитивной цепочки: 11
Длинна аддитивной цепочки: 14
Аддитивная цепочка: 1 2 4 8 16 24 48 52 104 208 416 832 1664 1688 1689
Time: 93.91579 с

n = 1993
Длина минимальной аддитивной цепочки: 11
Длинна аддитивной цепочки: 14
Аддитивная цепочка: 1 2 4 8 16 32 33 49 98 196 392 784 1568 1960 1993
Time: 74.21809 с

n = 2101
Длина минимальной аддитивной цепочки: 12
Длинна аддитивной цепочки: 15
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 2048 2080 2096 2100 2101
Time: 805.81512 с

n = 4137
Длина минимальной аддитивной цепочки: 13
Длинна аддитивной цепочки: 15
Аддитивная цепочка: 1 2 4 8 16 32 64 128 256 512 1024 2048 4096 4128 4136 4137
Time: 196.01424 с



Алгоритм дробления вектора индексов был применем к тем же числам, что и алгоритм Яо: 1127, 1689, 1993, 2101, 4137. Видно, что длина аддитивных цепочек, полученных алгоритмом дробления вектора индексов, меньше чем у цепочек, полученных алгоритмом Яо. Но для получения результата понадобилось значительно больше времени, разница в требуемом времени от 42,18 с для 1127 и до 805,72 с для 2101.

4. Проверить гипотезу Шольца–Брауэра для всех натуральных $ 1 \le n \le 12 $ на алгоритме дробления вектора индексов. Результаты оформить в виде таблицы. Сделать выводы.

Гипотеза Шольца-Брауэра:
$$ l(2^n-1) \leq l(n)+n-1 $$

Для проверки гипотезы используем код из предыдущего пункта, чтобы получить длины цепочек.

In [8]:
from math import log
import time

def next_ind_vec(part):
    for i in range(len(part) - 1, 0, -1):
        if part[i] > 1:
            part[i] -= 1
            for j in range(i + 1, len(part)):
                part[j] = j + 1
            return part
    return []

def search_chain(ind_vec):
    chain = [1]
    for i in ind_vec:
        chain.append(chain[-1] + chain[i-1])
    return chain

def splitt_vector_index(n):
    if n < 4:
        return [a for a in range(1, n+1)]
    for m in range(ceil(log(n, 2)), floor(log(n, 2)) + bin(n).count("1")):
        q = m // 2
        fix_part = [a for a in range(1, q+1)]
        var_part = [a for a in range(q+1, m+1)]
        while len(fix_part):   
            chain = search_chain(fix_part + var_part)
            a_min = chain[q] + m - q
            a_max = chain[q]*2**(m-q)
            if a_min <= n <= a_max:
                while len(var_part):      
                    chain = search_chain(fix_part + var_part)
                    if chain[-1] == n:
                        return search_chain(fix_part + var_part)
                    var_part = next_ind_vec(var_part)
            fix_part = next_ind_vec(fix_part)
            var_part = [i for i in range(q+1, m+1)]
            

min_len = [0, 2, 4, 5, 7, 8, 10, 10, 12, 13, 15, 15]
for n in range(1, 13):
    chain = splitt_vector_index(n)
    print('n =', n)
    if min_len[n-1] <= len(chain)+n-1:
        print(min_len[n-1], '<=', len(chain)+n-1, ' true')
    else:
        print(' false')
        print(chain_n)

n = 1
0 <= 1  true
n = 2
2 <= 3  true
n = 3
4 <= 5  true
n = 4
5 <= 6  true
n = 5
7 <= 8  true
n = 6
8 <= 9  true
n = 7
10 <= 11  true
n = 8
10 <= 11  true
n = 9
12 <= 13  true
n = 10
13 <= 14  true
n = 11
15 <= 16  true
n = 12
15 <= 16  true


Получим:

|  n | Длина по Ш-Б | Получ. длина | Итог |
|:--:|:------------:|:------------:|:----:|
|  1 |       0      |       1      |  Ок  |
|  2 |       2      |       3      |  Ок  |
|  3 |       4      |       5      |  Ок  |
|  4 |       5      |       6      |  Ок  |
|  5 |       7      |       8      |  Ок  |
|  6 |       8      |       9      |  Ок  |
|  7 |      10      |      11      |  Ок  |
|  8 |      10      |      11      |  Ок  |
|  9 |      12      |      13      |  Ок  |
| 10 |      13      |      14      |  Ок  |
| 11 |      15      |      16      |  Ок  |
| 12 |      15      |      16      |  Ок  |

Как видно по таблице, гипотеза Шольца-Брауэра потверждается для $ 1 \le n \le 12 $.

## Выводы

В ходе работы были изучены алгоритмы Яо и дробления вектора индексов. Было проведено исследование алгоритмов формирования аддитивных цепочек.

Вручную были были построены последовательности вычислений бинарным методом и методом множителей. Сравнение результатов показало, что бинарный метод работает медленей для тех чисел, в двоичной записи которых преобладают единицы.
При помощи SageMath были реализованы алгоритмы Яо и дробления вектора индексов, при помощи второго алгоритма была проверена гипотеза Шольца-Брауэра для чисел от 1 до 12 включительно. Было проведено сравнение обоих алгоритмов, которое показало, что алгоритм Яо работает быстрее, но получаемые цепочки длиньше чем у алгоритма дробления вектора индексов.