# Практическая работа №1: Исследование алгоритмов формирования аддитивных цепочек

Выполнил студент гр. 0392 Чернов Арсений, вариант 88.

## Цель работы

Формирование представления о аддитивных цепочках, выработать умение составлять и применять алгоритмы для нахождения минимальных
аддитивных цепочек для заданного числа, привить навык использования систем компьютерной математики для реализации алгоритмов.

## Основные теоретические положения

Аддитивной цепочкой для $ n \in \mathbb{N} $ называется последовательность натуральных чисел

$$ 1 = a_0, a_1, ..., a_r = n,\\ $$
где каждый элемент последователньости равен сумме каких-то двух предыдущих:

$$ a_i = a_j + a_k, \quad k \le j \le i, \quad i = 1, 2, ..., r\\ $$
$ l(n) = r $ - наименьшая длина аддитивной цепочки для $ n \in \mathbb{N} $.

Для метода множителей: $ \quad l(mn) \le l(m) + l(n)$

Для бинарного метода: $ l(n) = \lambda(n) + \nu(n) - 1, $

где $ \lambda (n) = \lfloor lb(n) \rfloor, \nu(n) $ - вес Хэмминга числа $n$ (количество единиц в двоичной записи).

Для m-арного метода: $ \quad l(n) \le m - 2 + (k + 1)t, $ 

где $m = 2^k, n = \sum_{j = 0}^t d_j m^{t-j} $

Для SX-метода: $\quad l(n) \le \lambda (n) + \nu (n) - 1$


Пара $ (j, k), 0 \le k \le j < i $ называется **шагом** $i$.Если существует более одной пары $(j, k)$, полагаем $j$ наибольшим.

### Виды шагов:
* удвоение: $ j = k = i - 1 $
* звёздный шаг: $ j = i - 1 $ (линейный шаг)
* малый шаг: $ \lambda (a_i) = \lambda (a_i - 1) $

### Свойства видов шагов:
* шаг 1 - всегда удвоение
* удвоение - звёздный шаг, но никогда не малый
* если $i$-ый шаг не малый, то $(i+1)$-ый шаг либо малый, либо звёздный, либо оба
* за удвоением всегда следует звёздный шаг
* если $(i+1)$-ый шаг не звёздный и не малый, то $i$-ый шаг должен быть малым

### Теорема:

Если аддитивная цепочка содержит $d$ и $f = r - d$ неудвоений, то $n \le 2^{d-1} F_{f+3}$, где $F_j$ - число Фиббоначи

### Следствие:

Если аддитивная цепочка содержит $f$ удвоений и $S$ малых шагов, то

${S \le f \le} {S \over {1 - lb(\varphi)}}$, где $\varphi = {{\sqrt{5} + 1} \over 2} $ - золотое сечение

### Алгоритм Брауэра:

Для $n \in \mathbb{N}$ при заданном $k \in \mathbb{N}$ можно построить цепочку Брауэра с помощью рекуррентной формулы:

$ B_k (n) =
\begin{cases}
1, 2, 3, ..., 2^k - 1, \quad n < 2^k \\
B_k (q), 2q, 4q, ..., 2^k q, n, \quad n \ge 2^k
\end{cases} \\ $
$ q = \lfloor {n \over 2^k} \rfloor $

Длина цепочки

$ l_B (n) = j(k + 1) + 2^k - 2, $

при условии, что $jk \le \lambda (n) \le (j+1)k$

Длина будет минимальной для больших $n$, если положить $k = \lambda \lambda (n) - 2 \lambda \lambda \lambda (n)$

**Ход алгоритма:**

* Задаётся некий параметр $k$ для $n$.
Вычисляются вспомогательные числа:

$ d = 2^k, \hspace{0.2cm} q_1 = [ {n \over d} ], \hspace{0.2cm} r_1 = n \hspace{0.2cm} mod \hspace{0.2cm} d => n = q_1 d + r_1 \quad (0 \le r_1 < d) \\ $
$ q_2 = [ {q_1 \over d} ], \hspace{0.2cm} r_2 = q_1 \hspace{0.2cm} mod \hspace{0.2cm} d => q_1 = q_2 d + r_2 \quad (0 \le r_2 < d) \\ $
* Данная процедура продолжается, пока не появится $q_s < d.$ Следовательно, $q_{s-1} = q_s d + r_s$
* Таким образом, n имеет вид

$ n = 2^k q_1 + r_1 = 2^k (2^k q_2 + r_2) + r_1 = ... = 2^k (2^k (... (2^k q_s + r_s ) ... ) + r_2 ) + r_1 . $

$ B_n (n): 1, 2, 3, ..., 2^k - 1, \\ $
$ 2q_s, 4q_s, 8q_s, ..., 2^k q_s, 2^k q_s + r_s, \\ $
$ 2q_{s-1}, 4q_{s-1}, 8q_{s-1}, ..., 2^k q_{s-1}, 2^k q_{s-1} + r_{s-1}, \\ $
$ ..., \\ $
$ ..., 2^k q_1, 2^k q_1 + r_1 = n. $

### Алгоритм Яо:

* Обладает такой же вычислительной мощностью, что и алгоритм Брауэра
* Выбирается $k \ge 2$, $n$ раскладывается в $2^k$-ой системе счисления:
$ n = \sum_{i = 0}^j a_i 2^{ik} , a_j \ne 0 $
* Введём функцию d:
$ d(z) = \sum_{i: a_i = z} 2^{ik} $

**Ход алгоритма:**

* Базовая последовательность: $1, 2, 4, ..., 2^{\lambda(n)}$
* Вычисление значений $d(z)$ для всех $z \in \{ 1, 2, ..., 2^k - 1\}, \quad d(z) \ne 0$
* Вычисление $zd(z)$ для всех $z$
* n раскладывается в виде
$$ n = \sum_{z = 1}^{2^k - 1} zd(z) $$

## Постановка задачи

Реализовать точные и приближённые алгоритмы нахождения минимальных аддитивных цепочек с использованием системы компьютерной математики SageMath, провести анализ алгоритмов. Полученные результаты содержательно проинтерпретировать.

## Выполнение работы

### Задание №1

Вручную (т.е. не реализовывая алгоритм на Sage) построить последовательность вычислений бинарным методом и методом множителей для $x^n$ для 2-3 значений 𝑛 (значение 𝑛 ⩾ 30 выбираются студентом самостоятельно). Сравнить количество операций для каждого метода, сделать выводы.

1.1. Бинарный метод "SX"

Пусть даны числа:

$ n = {33, 487, 989}\\ $

Переведём их с десятичной системы счисления в двоичную:

1. $ 33_{10}=1 \cdot 2^5 + 0 \cdot 2^4 + 0 \cdot 2^3 + 0 \cdot 2^2 + 0 \cdot 2^1 + 1 \cdot 2^0 = 100001_2\\ $

2. $ 487_{10}=1 \cdot 2^8 + 1 \cdot 2^7 + 1 \cdot 2^6 + 1 \cdot 2^5 + 0 \cdot 2^4 + 0 \cdot 2^3 + 1 \cdot 2^2 + 1 \cdot 2^1 + 1 \cdot 2^0 = 111100111_2\\ $

3. $ 989_{10}=1 \cdot 2^9 + 1 \cdot 2^8 + 1 \cdot 2^7 + 1 \cdot 2^6 + 0 \cdot 2^5 + 1 \cdot 2^4 + 1 \cdot 2^3 + 1 \cdot 2^2 + 0 \cdot 2^1 + 1 \cdot 2^0 = 1111011101_2\\ $

Теперь отнимем старший бит у чисел в двоичной системе счисления:

1. $ 100001_2 \rightarrow 00001_2\\ $

2. $ 111100111_2 \rightarrow 11100111_2\\ $

3. $ 1111011101_2 \rightarrow 111011101_2\\ $

Далее, проведём следующие замены:

$ "1" \rightarrow "SX"\\ $
$ "0" \rightarrow "S"\\ $

1. $ 00001_2 \rightarrow SSSSSX\\ $

2. $ 11100111_2 \rightarrow SXSXSXSSSXSXSX\\ $

3. $ 111011101_2 \rightarrow SXSXSXSSXSXSXSSX\\ $

Все преобразования проведены, осталось лишь посчитать необходимые степени и определить количество операций для вычисления, вспоминая обозначения операций:

$ "S" \rightarrow a^2\\ $
$ "X" \rightarrow a^{n+1}\\ $

1. $ SSSSSX: 1 \rightarrow 2 \rightarrow 4 \rightarrow 8 \rightarrow 16 \rightarrow 32 \rightarrow 33 $ (6 операций)

2. $ SXSXSXSSSXSXSX: 1 \rightarrow 2 \rightarrow 3 \rightarrow 6 \rightarrow 7 \rightarrow 14 \rightarrow 15 \rightarrow 30 \rightarrow 60 \rightarrow 120 \rightarrow 121 \rightarrow 242 \rightarrow 243 \rightarrow 486 \rightarrow 487 $ (14 операций)

3. $ SXSXSXSSXSXSXSSX: 1 \rightarrow 2 \rightarrow 3 \rightarrow 6 \rightarrow 7 \rightarrow 14 \rightarrow 15 \rightarrow 30 \rightarrow 60 \rightarrow 61 \rightarrow 122 \rightarrow 123 \rightarrow 246 \rightarrow 247 \rightarrow 494 \rightarrow 988 \rightarrow 989 $ (16 операций)

1.2. Бинарный метод возведения в степень справа налево

Пусть даны числа:

$ n = {33, 487, 989}\\ $

1. Для $ n = 33 $ - 7 операций

№ | N | Y | Z
--- | --- | --- | ---
1 | 33 | 1 | $$x$$
2 | 16 | $$x$$ | $$x^2$$
3 | 8 | $$x$$ | $$x^4$$
4 | 4 | $$x$$ | $$x^8$$
5 | 2 | $$x$$ | $$x^{16}$$
6 | 1 | $$x$$ | $$x^{32}$$
7 | 0 | $$x^{33}$$ | $$x^{32}$$

2. Для $ n = 487 $ - 10 операций

№ | N | Y | Z
--- | --- | --- | ---
1 | 487 | 1 | $$x$$
2 | 243 | $$x$$ | $$x^2$$
3 | 121 | $$x^3$$ | $$x^4$$
4 | 60 | $$x^7$$ | $$x^8$$
5 | 30 | $$x^7$$ | $$x^{16}$$
6 | 15 | $$x^7$$ | $$x^{32}$$
7 | 7 | $$x^{39}$$ | $$x^{64}$$
8 | 3 | $$x^{103}$$ | $$x^{128}$$
9 | 1 | $$x^{231}$$ | $$x^{256}$$
10 | 0 | $$x^{487}$$ | $$x^{256}$$

3. Для $ n = 989 $ - 11 операций

№ | N | Y | Z
--- | --- | --- | ---
1 | 989 | 1 | $$x$$
2 | 494 | $$x$$ | $$x^2$$
3 | 247 | $$x$$ | $$x^4$$
4 | 123 | $$x^5$$ | $$x^8$$
5 | 61 | $$x^{13}$$ | $$x^{16}$$
6 | 30 | $$x^{29}$$ | $$x^{32}$$
7 | 15 | $$x^{29}$$ | $$x^{64}$$
8 | 7 | $$x^{93}$$ | $$x^{128}$$
9 | 3 | $$x^{221}$$ | $$x^{256}$$
10 | 1 | $$x^{477}$$ | $$x^{512}$$
11 | 0 | $$x^{989}$$ | $$x^{512}$$

1.3. Метод множителей

Пусть даны числа:

$ n = {33, 487, 989}\\ $

1. Для $ n = 33 $ - 7 операций

$ 33 = 3 \cdot 11\\ $
$ x, x^2, x^3; y_1 = x^3\\ $
$ y_1, y_1^2, y_1^4, y_1^5, y_1^{10}, y_1^{11} = x^{33}\\ $

2. Для $ n = 487 $ - 12 операций

487 - простое число, потому вычисляем для 486

$ 486 = 2 \cdot 243\\ $
$ x, x^2; y_1 = x^2\\ $
$ 243 = 3 \cdot 81\\ $
$ y_1, y_1^2, y_1^3; y_2 = y_1^3\\ $
$ 81 = 3 \cdot 27\\ $
$ y_2, y_2^2, y_2^3; y_3 = y_2^3\\ $
$ 27 = 3 \cdot 9\\ $
$ y_3, y_3^2, y_3^3; y_4 = y_3^3\\ $
$ y_4, y_4^2, y_4^4, y_4^8, y_4^9 = x^{486}\\ $
$ x^{486}, x^{487}\\ $

3. Для $ n = 989 $ - 15 операций

$ 989 = 23 \cdot 43\\ $
$ x, x^2, x^4, x^5, x^{10}, x^{11}, x^{22}, x^{23}; y_1 = x^{23}\\ $
$ y_1, y_1^2, y_1^4, y_1^5, y_1^{10}, y_1^{20}, y_1^{21}, y_1^{42}, y_1^{43} = x^{989} $

Теперь сравним число операций в разных методах вычислений:

N | 1.1. | 1.2. | 1.3.
--- | --- | --- | ---
33 | 6 | 7 | 7
487 | 14 | 10 | 12
989 | 16 | 11 | 15

### Вывод

При малых числах n наиболее оптимально использовать бинарный метод "SX", хотя остальные методы несильно проигрывают. При уже больших числах n наиболее оптимально использовать бинарный метод возведения в степень справа налево, тогда как бинарный метод "SX" может довольно сильно проигрывать, а метод множителей может совсем немного или сильно проигрывать.

### Задание №2

Реализовать алгоритм Брауэра (для нечётных вариантов) и алгоритм Яо (для чётных вариантов) для вычисления приближённых аддитивных цепочек для различных чисел при варьировании параметра 𝑘, сопоставить длины полученных аддитивных цепочек с минимальной аддитивной цепочкой для заданного числа. Сделать выводы.

Напишем функцию разложения числа $ n $ в $ 2^k $-чной системе счисления:

In [1]:
import time
from math import log, ceil

def razlog_2k(n, k):
    cifr = []
    div = 1 << k
    while n > 0:
        cifr.append(n % div)
        n //= div
    return cifr

Теперь напишем функцию, которая возвращает значение $ d(z) $, а также добавляет элементы в аддитивную цепочку cep

In [2]:
def d_z(z, k, cifr, cep):
    d = 0
    for i in range(len(cifr)):
        if cifr[i] == z:
            s = 1 << (i * k)
            if d != 0:
                cep.append(d + s)
            d += s
    return d

Далее напишем функцию, которая возвращает значение $ z \cdot d(z) $ и добавляет её в цепочку. Вычисления происходят по бинарному алгоритму "справа налево"

In [3]:
def zd_z(z, dz, cep):
    t, old_dz = 0, dz
    while z != 0:
        if dz not in cep:
            cep.append(dz)
        if z % 2 != 0:
            if t != 0:
                cep.append(t + dz)
            t += dz
        dz *= 2
        z //= 2
    return t

Осталось реализовать сам алгоритм Яо. Сделаем же это!

In [4]:
def cepochka(n, k):
    cifr = razlog_2k(n, k)
    
    # базовая последовательность от 2^0 до 2^jk, j - max индекс цифры в 2^k-чной системе счисления
    cep = Sequence(1<<i for i in range((len(cifr)-1)*k+1))
    
    # вычисление d(z) для всех (кроме 0) цифр числа n в 2^k-чной системе счисления
    dz = {z:d_z(z, k, cifr, cep) for z in set(filter(lambda x: x != 0, cifr))}
    
    # вычисление z*d(z)
    zdz = Sequence(zd_z(i, dz[i], cep) for i in dz)
    
    # сумма всех z*d(z) с добавлением в цепочку
    n = zdz[0]
    for i in range(1, len(zdz)):
        n += zdz[i]
        cep.append(n)
    return cep

Для проверки работы алгоритма и составления вывода о её работе, проведём серию тестов

In [11]:
test_set = [4096, 1040, 1056, 8192, 2064]
for val in test_set:
    print("n = ", val)
    for k in range(3, 7):
        begin = time.time()
        cep = cepochka(val, k)
        end = time.time()
        print("k = ", k, "\t Цепочка: ", *cep)
        print("l(n) = ", len(cep)-1, "\t Затраченное время = ",
              round(end-begin, 5), " sec\tМинимальная длина = ", ceil(log(val, 2)))
    print("\n")

n =  4096
k =  3 	 Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 2048 4096
l(n) =  12 	 Затраченное время =  0.00017  sec	Минимальная длина =  12
k =  4 	 Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 2048 4096
l(n) =  12 	 Затраченное время =  0.00012  sec	Минимальная длина =  12
k =  5 	 Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 2048 4096
l(n) =  12 	 Затраченное время =  0.00014  sec	Минимальная длина =  12
k =  6 	 Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 2048 4096
l(n) =  12 	 Затраченное время =  0.00023  sec	Минимальная длина =  12


n =  1040
k =  3 	 Цепочка:  1 2 4 8 16 32 64 128 256 512 520 1040
l(n) =  11 	 Затраченное время =  0.00018  sec	Минимальная длина =  11
k =  4 	 Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 1040
l(n) =  11 	 Затраченное время =  0.00018  sec	Минимальная длина =  11
k =  5 	 Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 1040
l(n) =  11 	 Затраченное время =  0.00017  sec	Минимальная длина =  11
k =  6 	 Цепочка:  1 2 4 8 16 32 64 65 130 260 520 1040


Работа алгоритма Яо была протестирована при разных значениях параметра $k$. Алгоритм занял примерно от 1 до 4 $ 10^{-4} $ секунды при каждом запуске. При этом при разных $k$ длина цепочки была одинаковой. Также время работы для разных $k$ было примерно одинаковым.

Длина цепочки не превышала минимальную оценку. За минимальную оценку было взято значение $\lceil log_{2}n \rceil$, полученное с помощью бинарного метода "справа налево".

### Задание №3

Реализовать алгоритм дробления вектора индексов для нахождения минимальной звёздной цепочки для заданного числа. Протестировать алгоритм минимум для 5 значений 𝑛 > 1000. Указать, сколько времени потребовалось на поиск цепочки и какая цепочка получилась. Сравнить с предыдущими методами, сделать выводы.

Для алгоритма напишем функцию перехода к следующему вектору индексов (или его части, например, перебор половины вектора). Она будет возвращать True при полученном неединичном векторе или False при векторе из единиц.

In [6]:
import time
from math import log, ceil, floor

def new_vector(vect, start, end):
    i = end
    
    # найти самую старшую позицию с r_i > 1 и уменьшить r_i на 1
    while vect[i] == 1 and i >= start:
        i -= 1
    if i < start:
        return False
    vect[i] -= 1
    
    # выставить все следующие индексы в max
    for j in range(i + 1, end + 1):
        vect[j] = j + 1
    return True

Теперь напишем функцию для вычисления аддитивной цепочки по вектору индексов

In [7]:
def add_cep(vect):
    cep = [1]
    for i in vect:
        cep.append(cep[-1] + cep[i - 1])
    return cep

Осталось реализовать алгоритм дробления вектора индексов. Сделаем это!

In [8]:
def index_vector_cepochka(n):
    if n < 3:
        return list(range(1, n + 1))
    for m in range(ceil(log(n, 2)), floor(log(n, 2)) + bin(n).count('1')):
        vect = list(range(1, m + 1))
        q = m // 2
        vect[q - 1] += 1 # увеличить на 1, чтобы в цикле получить нужное значение
        while new_vector(vect, 0, q - 1):
            a = add_cep(vect)
            if a[m] == n:
                return a
            elif n >= a[q] + m - q and n <= a[q] * 2**(m - q):
                while new_vector(vect, q, len(vect) - 1):
                    a = add_cep(vect)
                    if a[m] == n:
                        return a
                # снова выставить правую часть в максимум и перебирать левую половину
                for i in range(q, len(vect)):
                    vect[i] = i + 1

Для проверки работы алгоритма и составления вывода о её работе, проведём серию тестов

In [12]:
test_set = [4096, 1040, 1056, 8192, 2064]
for val in test_set:
    print("n = ", val)
    begin = time.time()
    cep = index_vector_cepochka(val)
    end = time.time()
    print("Цепочка: ", *cep)
    print("l(n) = ", len(cep) - 1, "\t Затраченное время = ",
              round(end-begin, 5), " sec\tМинимальная длина = ", ceil(log(val, 2)))
    print("\n")

n =  4096
Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 2048 4096
l(n) =  12 	 Затраченное время =  9e-05  sec	Минимальная длина =  12


n =  1040
Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 1040
l(n) =  11 	 Затраченное время =  0.00036  sec	Минимальная длина =  11


n =  1056
Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 1056
l(n) =  11 	 Затраченное время =  0.00034  sec	Минимальная длина =  11


n =  8192
Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 2048 4096 8192
l(n) =  13 	 Затраченное время =  8e-05  sec	Минимальная длина =  13


n =  2064
Цепочка:  1 2 4 8 16 32 64 128 256 512 1024 2048 2064
l(n) =  12 	 Затраченное время =  0.00032  sec	Минимальная длина =  12




Алгоритм был протестирован для тех же чисел, что и алгоритм Яо. Длины полученных звёздных цепочек получились такими же, как для алгоритма Яо, для всех чисел. На данных числах алгоритм сработал быстрее, т.к. эти числа легко раскладываются в сумму степеней двойки: $ 4096 = 2^{12}, 1040 = 2^{10} + 2^4, 1056 = 2^{10} + 2^5, 8192 = 2^{13}, 2064 = 2^{11} + 2^{4} $.

### Задание №4

Проверить гипотезу Шольца–Брауэра для всех натуральных 1 ⩽ 𝑛 ⩽ 12 на алгоритме дробления вектора индексов. Результаты оформить в виде таблицы. Сделать выводы.

Гипотеза Шольца-Брауэра представляется следующим неравенством:

$$l(2^n-1) \leq l(n)+n-1.$$

Она была доказана только для звёздных цепочек.

Проверим гипотезу с помощью следующей программы:

In [ ]:
for i in range (1, 13):
    cep_2n = index_vector_cepochka(2**i - 1)
    cep_n = index_vector_cepochka(i)
    print("n =", i, end='')
    if len(cep_2n) - 1 <= len(cep_n) + i - 2:
        print("\tTRUE\t", len(cep_2n) - 1, '<=', len(cep_n) + i - 2)
    else:
        print("\tFALSE")
        print(cep_n)
        break

n = 1	TRUE	 0 <= 0
n = 2	TRUE	 2 <= 2
n = 3	TRUE	 4 <= 4
n = 4	TRUE	 5 <= 5
n = 5	TRUE	 7 <= 7
n = 6	TRUE	 8 <= 8
n = 7	TRUE	 10 <= 10
n = 8	TRUE	 10 <= 10


Оформив результат в виде таблицы, получим:


| N  | Верно |Неравенство|
|---|---|---|
| 1 | Да | 0 <= 0 |
| 2 | Да | 2 <= 2 |
| 3 | Да | 4 <= 4 |
| 4 | Да | 5 <= 5 |
| 5 | Да | 7 <= 7 |
| 6 | Да | 8 <= 8 |
| 7 | Да | 10 <= 10 |
| 8 | Да | 10 <= 10 |
| 9 | Да | 12 <= 12 |
| 10 | Да | 13 <= 13 |
| 11 | Да | 15 <= 15 |
| 12 | Да | 15 <= 15 |

Таким образом, гипотеза Шольца-Брауэра была проверена для всех чисел $1 \leq n \leq 12.$ Неравенство оказалось верно во всех случаях.

### Задание №5*

Найти или предложить собственные модификации алгоритмов и привести описание модификаций. Реализовать модифицированные алгоритмы и сравнить их мощность.

## Вывод

В данной работе были исследованы алгоритмы построения минимальных аддитивных цепочек для различных чисел.

Были реализованы алгоритмы Яо и дробления вектора инедексов. С помощью алгоритма дробления вектора индексов была проверена гипотеза Шольца-Брауэра для чисел $1 \leq n \leq 12.$.