# Практическая работа №1: Исследование алгоритмов формирования аддитивных цепочек

Выполнила студентка гр. 0304 Говорющенко Анастасия, вариант 29.

## Цель работы

Формирование представления о аддитивных цепочках, выработать умение составлять и применять алгоритмы для нахождения минимальных
аддитивных цепочек для заданного числа, привить навык использования
систем компьютерной математики для реализации алгоритмов.

## Основные теоретические положения

<p>Аддитивной цепочкой для натурального числа n называется последовательность натуральных чисел $$ 1 = a_0, a_1, ..., a_r = n, $$ где каждый элемент последовательности равен сумме каких-либо двух предыдущих: $$ a_i = a_j + a_k, k \leq j < i, i = 1, 2, ..., r $$<p>
<br>
<p>$l(n) = r$ - наименьшая длина аддитивной цепочки $n \in  N$  </p>
<p>Для метода множителей: $l(mn) \leq l(m) + l(n)$</p>
<p>Для бинарного метода: $ l(n) = λ(n) + \nu(n) -1 $, где $ λ(n) = \lfloor lb(n)\rfloor, \nu(n) - $ вес Хэмминга числа n (количество единиц в двоичной записи).</p>
<p>Для m-арного метода: $l(n) \leq m - 2 + (k+1)t$, где $m = 2^k, n = \varSigma_{j=0}^t d_j m^{t-j}$ </p>   
<p>Для SX-метода: $ l(n) \leq λ(n) + \nu(n) -1 $</p>  
<p>Пара $(j,k), 0 \leq k \leq j < i$ называется шагом $i$. Если существует более одной пары $(j,k)$, полагаем j наибольшим. </p>    
  
    
### Виды шагов:    
<ul>
    <li> удвоение: $ j = k = i - 1 $</li>
    <li> звездный шаг: $ j = i - 1 $</li>
    <li> малый шаг: $ \lambda(a_i) = \lambda(a_{i-1}) $</li>   
</ul>
        
### Свойства видов шагов:
<ul>
    <li> Шаг 1 всегда удвоение.</li>
    <li> Удвоение - звездный шаг, но никогда не малый.</li>
    <li> За удвоением всегда следует звездный шаг.</li>
    <li> Если $i$-ый шаг не малый, то $(i+1)$-ый либо малый, либо звездный, либо оба. </li>
    <li> Если $(i+1)$-ый шаг не звездный и не малый, то $i$-ый шаг должен быть малым.</li>
</ul>      

### Теорема:
<p>Если аддитивная цепочка включает $d$ удвоений и $f = r - d$ неудвоений, то $n \leq 2^{d-1}F_{f+3}$, где $F_j $ - число Фиббоначи.</p>

### Следствие:
<p>Если аддитивная цепочка включает $f$ неудвоений и $s$ малых шагов, то $$ s \leq f \leq \frac{s}{1-lb(\phi)},$$ где $\phi = \frac{\sqrt 5 +1}{2}$</p>

### Алгоритм Брауэра
<p>Для $n \in N$ при заданном $k \in N$ можно построить цепочку Брауэра с помощью рекуррентной формулы: 
$$B_k(n) = \begin{cases}
1, 2, 3, ..., 2^k-1& \text{n < 2^k},\\
B_k(q), 2q, 4q, ..., 2^kq, n& \text{$n \geq 2^k, q = \lfloor \frac{n}{2^k}\rfloor$}.
\end{cases}$$</p>
<p>Длина цепочки: $$ lg(n) = j(k+1) + 2^k -2, $$ при условии, что $jk \leq \lambda(n) < (j+1)k$ </p>
<p>Длина будет минимальной для больших $n$, если положить $k =\lambda\lambda(n)-2\lambda\lambda\lambda(n) $</p>

#### Ход алгоритма
<ul>
    <li>Задается некий фиксированный параметр $k$ для $n$. Выполняется вычисление вспомогательных чисел:
    $$ d = 2^k, q = \lfloor \frac{n}{d}\rfloor, r_1 = n mod d => n = q_1d+r_1 (0\leq r_1 < d)   $$
    $$ q_2 = \lfloor \frac{q_1}{d}\rfloor, r_2 = q_1 mod d => q_1 = q_2d+r_2 (0\leq r_2 < d)   $$
    </li>
    <li>Данная процедура продолжится до тех пор, пока не появится такое $q_s < d$, что $ q_{s-1} = q_sd+r_s$</li>
    <li>Таким образом, $n$ имеет вид: $$n = 2^kq_1+r_1 = 2^k(2^kq_2+r_2)+r_1 = ... = 2^k(2^k(...(2^kq_s+r_s)...)+r_2)+r_1 $$</li>
</ul>    
<p>$$B_k(n) = 1, 2, 3, ... , 2^k-1, 2q_s, 4q_s, 8q_s, ... , 2^kq_s, 2^kq_s+r_s, 2q_{s-1}, 4q_{s-1}, 8q_{s-1}, ... , 2^kq_{s-1}, 2^kq_{s-1}+r_{s-1}, ... , 2^kq_1, 2^kq_z+r_1 = n$$</p>

### Алгоритм Яо
<ul>
    <li>Имеет ту же вычислительную сложность, что и алгоритм Брауэра.</li>
    <li>Выбирается $k \geq 2, n$ раскладывается в $2^k$-ой системе счисления: $$n = \sum_{i=0}^j a_i2^{ik}, a_j ≠ 0 $$</li>
    <li>Введем функцию $d$:$$ d(z) = \sum_{i:a_i=z} 2^{ik}$$</li>
</ul>

#### Ход алгоритма:
<ul>
    <li>Базовая последовательность: $1, 2, 4, ... , 2^{\lambda(n)}$</li>
    <li>Вычисление значений $d(z)$ для всех $z \in {1, 2, ..., 2^k-1}, d(z)≠0$</li>
    <li>Вычисление $zd(z) для всех z$</li>
    <li> $n$ раскладывается в виде:
    $$n = \sum_{z=1}^{2^k-1} zd(z)$$</li>
</ul>

## Постановка задачи

Реализовать точные и приближённые алгоритмы нахождения минимальных аддитивных цепочек с использованием системы компьютерной математики SageMath, провести анализ алгоритмов. Полученные результаты
содержательно проинтерпретировать.

## Порядок выполнения работы
<ol>
<li> Вручную (т.е. не реализовывая алгоритм на Sage) построить последовательность вычислений бинарным методом и методом множителей для $𝑥^𝑛$ для 2-3 значений 𝑛 (значение $𝑛 \geq 30$ выбираются студентом самостоятельно). Сравнить количество операций для каждого метода, сделать выводы.

<li> Реализовать алгоритм Брауэра (для нечётных вариантов) и алгоритм Яо (для чётных вариантов) для вычисления приближённых аддитивных цепочек для различных чисел при варьировании параметра 𝑘, сопоставить длины полученных аддитивных цепочек с минимальной аддитивной цепочкой для заданного числа. Сделать выводы.

<li> Реализовать алгоритм дробления вектора индексов для нахождения минимальной звёздной цепочки для заданного числа. Протестировать алгоритм минимум для 5 значений $𝑛 > 1000$. Указать, сколько времени потребовалось на поиск цепочки и какая цепочка получилась. Сравнить с предыдущими методами, сделать выводы.

<li> Проверить гипотезу Шольца–Брауэра для всех натуральных $1 \leq 𝑛 \leq 12$ на алгоритме дробления вектора индексов. Результаты оформить в виде таблицы. Сделать выводы.

<li> Найти или предложить собственные модификации алгоритмов и привести описание модификаций. Реализовать модифицированные
алгоритмы и сравнить их мощность.


## Выполнение работы

1. Построим последовательность вычислений бинарным методом для $x^n$ для $n = 67, 111$
<br>
**Бинарный метод**
$n = 67: $

| #   	| N    	|  Y     	|  Z     	|
|-----	|------	|--------	|--------	|
|  0  	|  67  	|  1     	| \|x    	|
|  1  	|  33  	|  x     	| x^2    	|
|  2  	|  16  	|  x^3   	|  x^4   	|
|  3  	|  8   	|  x^3   	|  x^8   	|
|  4  	|  4   	|  x^3   	|  x^16  	|
|  5  	|  2   	|  x^3   	|  x^32  	|
|  6  	|  1   	|  x^3   	|  x^64  	|
|  7  	|  0   	|  x^67  	|  x^64  	|

Метод занял 8 операций.

$n = 111$

| # 	| N   	|  Y    	|  Z   	|
|---	|-----	|-------	|------	|
| 0 	| 111 	| 1     	| x    	|
| 1 	| 55  	| x     	| x^2  	|
| 2 	| 27  	| x^3   	| x^4  	|
| 3 	| 13  	| x^7   	| x^8  	|
| 4 	| 6   	| x^15  	| x^16 	|
| 5 	| 3   	| x^15  	| x^32 	|
| 6 	| 1   	| x^47  	| x^64 	|
| 7 	| 0   	| x^111 	| x^64 	|

Метод занял 11 опрераций.

$n = 127$

| # 	| N   	|  Y    	|  Z   	|
|---	|-----	|-------	|------	|
| 0 	| 127 	| 1     	| x    	|
| 1 	| 63  	| x     	| x^2  	|
| 2 	| 31  	| x^3   	| x^4  	|
| 3 	| 15  	| x^7   	| x^8  	|
| 4 	| 7   	| x^15  	| x^16 	|
| 5 	| 3   	| x^31  	| x^32 	|
| 6 	| 1   	| x^63  	| x^64 	|
| 7 	| 0   	| x^127 	| x^64 	|

Метод занял 12 операций.

**Метод множителей**
$n = 67: $
$$x^{67} = x*x^{66} = x*(x^{33})^2 = x*((x^{11})^3)^2 = x*(x^{11}*(x^{11})^2)^2 , $$ где $$x^{11} = x*x^{10} = x*(x^5)^2 = x*(x*(x^2)^2)^2$$

Метод занял 9 операций.

$n = 111: $
$$ x^{111} = (x^{37})^3 = x^{37} * (x^{37})^2 $$
$$x^{37} = x * x^{36} = x*(x^{18})^2 = x*((x^{9})^2)^2 = x*(((x^2*x)^3)^2)^2$$

Метод занял 9 операций.

$n = 127$
$$x^{127} = x * x^{126} = x * (x^{63})^2 = x * ((x^{21})^3)^2$$
$$x^{21} = (x^7)^3 = (x*x^6)^3 = (x*(x^3)^2)^3$$

Метод занял 10 опяраций.
<br>
#### Итоги
|     	| Бинарный метод 	|  Метод множителей 	|
|-----	|----------------	|-------------------	|
| 67  	| 8              	| 9                 	|
| 111 	| 11             	| 9                 	|
| 127 	| 12             	| 10                	|

<p>Исходя из таблицы можно сделать вывод, что бинарный метод работает хуже в тех случаях, когда в двоичной записи числа содержиться большое количество единиц. Зависимость числа операций от количества единиц в двоично записи - вес Хэмминга - подтверждается следующей формулой $l(n) = \lambda(n) + \nu(n) -1$  </p>

2. Реализуем алгоритм Брауэра для вычисления приближенных аддитивных цепочек

In [2]:
#перевод в 2^k с.с
def shift_num_sys(n, k):
    new_num = []
    divisor = 1 << k
    while n > 0:
        new_num.append(n%divisor)
        n = n//divisor
    new_num.reverse()
    return new_num

#Возвращает "количество цифр в двоичной системе счисления - 1"
def _lambda(n):
    return len(shift_num_sys(n, 1))-1

#Минимальная дляна цепочки
def chain_length(n):
    return int(_lambda(n) + _lambda(n)/(_lambda(_lambda(n))) + (_lambda(n)*_lambda(_lambda(_lambda(n))))/((_lambda(_lambda(n)))**2))

#k при котором длина аддитивной цепочки будет минимальна
def best_k(n):
    return _lambda(_lambda(n))-2*_lambda(_lambda(_lambda(n)))


def brouwer(n, k):
    br_chain = []
    n_in_k = shift_num_sys(n, k)
    max_digit = max(n_in_k)
    for i in range(1, max_digit+1):
        br_chain.append(i)
    intermediate = 0
    for z in range(len(n_in_k)):
        temp = n_in_k[z]
        intermediate += temp
        if z != 0:
            br_chain.append(intermediate)
        if intermediate == n:
            break
        for j in range(k):
            intermediate *= 2
            br_chain.append(intermediate)
    return sorted(set(br_chain))


def chain_size(_chain):
    return len(_chain)-1


test_set = [31415, 2000, 5264, 16971, 953]
for val in test_set:
    print("TESTING BRAUWER'S ALGORITHM ON VALUE ", val)
    bk = best_k(val)
    min_chain = brouwer(val, bk)
    print("best_k = ", bk, "\t CHAIN: ", *min_chain)
    print("l(n) = ", chain_size(min_chain))
    for k in range(1, 7):
        chain = brouwer(val, k)
        print("k = ", k, "\t CHAIN: ", *chain)
        print("l(n) = ", chain_size(chain),  "\tMinimal length = ", chain_length(val))
    print("\n")

TESTING BRAUWER'S ALGORITHM ON VALUE  31415
best_k =  1 	 CHAIN:  1 2 3 6 7 14 15 30 60 61 122 244 245 490 980 981 1962 1963 3926 7852 7853 15706 15707 31414 31415
l(n) =  24
k =  1 	 CHAIN:  1 2 3 6 7 14 15 30 60 61 122 244 245 490 980 981 1962 1963 3926 7852 7853 15706 15707 31414 31415
l(n) =  24 	Minimal length =  20
k =  2 	 CHAIN:  1 2 3 4 7 14 28 30 60 120 122 244 488 490 980 1960 1963 3926 7852 7853 15706 31412 31415
l(n) =  22 	Minimal length =  20
k =  3 	 CHAIN:  1 2 3 4 5 6 7 14 28 56 61 122 244 488 490 980 1960 3920 3926 7852 15704 31408 31415
l(n) =  22 	Minimal length =  20
k =  4 	 CHAIN:  1 2 3 4 5 6 7 8 9 10 11 14 28 56 112 122 244 488 976 1952 1963 3926 7852 15704 31408 31415
l(n) =  25 	Minimal length =  20
k =  5 	 CHAIN:  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 60 120 240 480 960 981 1962 3924 7848 15696 31392 31415
l(n) =  41 	Minimal length =  20
k =  6 	 CHAIN:  1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23

Можно заметить, что по мере увеличения $k$ длина цепочки значительно увеличивается и становится значительно больше минимальной длины. Для того чтобы получать оптимальную длину аддитивной цепочки $k$ должно быть совсем невелико по сравнению с $n$. Такое значение получается при применении формулы $k = \lambda\lambda(n)-2\lambda\lambda\lambda(n) $, для небольших чисел $k$ следует взять равным 1 или 2.

3. Реализуем алгоритм дробления вектора индексов для нахождения минимальной звёздной цепочки для заданного числа.

In [12]:
import time
from math import log, ceil, floor

def _lambda(n):
    return len(shift_num_sys(n, 1))-1

def make_chain(vec):
    chain = [1]
    for i in vec:
        chain.append(chain[-1] + chain[i-1])
    return chain


def dec_vector(vector, start, end):
    # устанавливаем начальный индекс на конец
    i = end
    # проверяем является ли цифра на данной позиции 1, если да, то смещаемся на одну позицию влево
    while vector[i] == 1 and i >= start:
        i -= 1
    # если все элементы от начала до конца равно 1, то уменьшение вектора невозможно
    if i < start:
        return False
    # уменьшаем первый, больший 1, элемент
    vector[i] -= 1
    # выставить все следующие индексы в максимальное значение
    for j in range(i+1, end+1):
        vector[j] = j+1
    return True


def fraction(n):
    if n < 3:
        return list(range(1, n + 1))
    _l = ceil(log(n, 2))
    new_n = shift_num_sys(n, 1)
    nu = new_n.count(1)
    l_ = floor(log(n, 2))
    for m in range(_l, l_+ nu +1):
        vector = list(range(1, m+1))
        q = m//2
        vector[q-1] += 1
        while dec_vector(vector, 0, q-1):
            a = make_chain(vector)
            if a[m] == n:
                return a
            elif (n >= a[q]+m-q) and (n <= a[q]*2**(m-q)):
                while dec_vector(vector, q, len(vector)-1):
                    a = make_chain(vector)
                    if a[m] == n:
                        return a
                for i in range(q, len(vector)):
                    vector[i] = i+1

                    
test_set = [1033, 1040, 2176, 2000, 1234]
for val in test_set:
    print("TESTING FRACTION ON VALUE ", val)
    start = time.time()
    chain = fraction(val)
    end = time.time()
    print("CHAIN: ", *chain)
    print("l(n) = ", chain_size(chain),  "Time elapsed = ", round(end-start, 5), "sec\tMinimal length = ", ceil(log(val, 2)))
    print("\n")                

TESTING FRACTION ON VALUE  1033
CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 1032 1033
l(n) =  12 Time elapsed =  60.35923 sec	Minimal length =  11


TESTING FRACTION ON VALUE  1040
CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 1040
l(n) =  11 Time elapsed =  0.00013 sec	Minimal length =  11


TESTING FRACTION ON VALUE  2176
CHAIN:  1 2 4 8 16 32 64 128 256 512 1024 2048 2176
l(n) =  12 Time elapsed =  0.0001 sec	Minimal length =  12


TESTING FRACTION ON VALUE  2000
CHAIN:  1 2 4 8 16 32 64 128 256 384 400 800 1600 2000
l(n) =  13 Time elapsed =  273.6744 sec	Minimal length =  11


TESTING FRACTION ON VALUE  1234
CHAIN:  1 2 4 8 16 32 64 128 144 272 544 1088 1232 1234
l(n) =  13 Time elapsed =  1657.05268 sec	Minimal length =  11




Алгоритм дробления вектора индексов был протестирован на наборе [1033, 1040, 2176, 2000, 1234]. Минимальное количество времени потребовалось для вычисления чисел $1040 = 2^{10} + 2^4$ и $2176 = 2^{11} + 2^7$, а максимальное для числа 1234.  Такое долгое время работы объясняется тем, что в алгоритме происходит перебор различных векторов индексов, отчего алгоритм имеет факториальную сложность: $O( \sum(m-1)!)$.

4. Проверим гипотезу Шольца-Брауэра для чисел $ 1 \leq n \leq 12$ с помощью алгоритма дробления вектора индексов.

Гипотеза Шольца-Брауэра: $$ l(2^n -1) \leq l(n) + n -1$$

Код для проверки:

In [17]:
for i in range (1, 13):
    chain_2n = fraction(2**i-1)
    chain_n = fraction(i)
    print("n = ", i, end='')
    if len(chain_2n)-1 <= len(chain_n)+i-2:
        print("\tTrue\t", len(chain_2n)-1, '<=', len(chain_n)+i-2)
    else:
        print("\tFalse")
        print(chain_n)
        break

n =  1	True	 0 <= 0
n =  2	True	 2 <= 2
n =  3	True	 4 <= 4
n =  4	True	 5 <= 5
n =  5	True	 7 <= 7
n =  6	True	 8 <= 8
n =  7	True	 10 <= 10
n =  8	True	 10 <= 10
n =  9 	True	 12 <= 12
n = 10 	True	 13 <= 13
n = 11 	True	 15 <= 15
n = 12 	True	 15 <= 15


Таким образом, гипотеза Шольца-Брауэра была проверена для всех чисел $ 1 \leq n \leq 12 $. Неравенство оказалось верно во всех случаях.

## Выводы

В данной работе были исследованы алгоритмы построения минимальных адитивных цепочек для натуральных чисел.
<br>
Был реализован алгоритм Брауэра и алгоритм дробления вектора индексов. Также были рассмотрены бинарный алгоритм построения аддитивной цепочки и метод множителей. Были приобретены навыки работы с системы компьютерной математики SageMath для реализации заданных алгоритмов. На практике была проверена гиптоеза Шольца-Брауэра.